accounts/urls.py
from django.urls import include, path
import django.contrib.auth.views as dj_auth_views
from .views import LoginView, LogoutView, PasswordChangeView, AccountSettingsView
import django_cas_ng.views

app_name = "accounts"

cas_patterns = [
    path("login/", django_cas_ng.views.LoginView.as_view(), name="cas_ng_login"),
    path("logout/", django_cas_ng.views.LogoutView.as_view(), name="cas_ng_logout"),
    path(
        "callback/",
        django_cas_ng.views.CallbackView.as_view(),
        name="cas_ng_proxy_callback",
    ),
]

accounts_patterns = [
    path("cas/", include(cas_patterns)),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_login/", dj_auth_views.LoginView.as_view(), name="password_login"),
    path("change_password/", PasswordChangeView.as_view(), name="change_password"),
    path("settings/", AccountSettingsView.as_view(), name="account_settings"),
]

urlpatterns = [
    path("", include(accounts_patterns)),
]

suggestions/urls.py
from django.urls import path
from .views import (
    SuggestionListView,
    AddSuggestionView,
    SuggestionView,
    UpvoteSuggestionView,
    DownvoteSuggestionView,
    AddSuggestionCommentView,
    ModifySuggestionCommentView,
)

app_name = "suggestions"

urlpatterns = [
    path("", SuggestionListView.as_view(), name="suggestions"),
    path("add/", AddSuggestionView.as_view(), name="add_suggestion"),
    path("item/<slug>/", SuggestionView.as_view(), name="suggestion"),
    path(
        "item/<slug>/upvote", UpvoteSuggestionView.as_view(), name="upvote_suggestion"
    ),
    path(
        "item/<slug>/downvote",
        DownvoteSuggestionView.as_view(),
        name="downvote_suggestion",
    ),
    path(
        "item/<slug>/add_comment",
        AddSuggestionCommentView.as_view(),
        name="add_suggestion_comment",
    ),
    path(
        "item/<slug>/modify_comment/<int:comment_id>",
        ModifySuggestionCommentView.as_view(),
        name="modify_suggestion_comment",
    ),
]

website/urls.py
from django.urls import path
from .views import MarkdownPageView

app_name = "website"

urlpatterns = [
    path("", MarkdownPageView.as_view(), {"slug": ""}, name="home"),
    path("<slug:slug>/", MarkdownPageView.as_view(), name="md_page"),
]

suggestions/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
from autoslug import AutoSlugField
from website.validators import MaxFileSizeValidator
from accounts.models import User
from inventory.models import Category, Tag
from comments.models import AbstractComment


class Suggestion(models.Model):
    title = models.CharField(verbose_name="titre du jeu", max_length=256, unique=True)
    slug = AutoSlugField(populate_from="title", unique=True)

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        verbose_name="prix en euros",
        validators=[MinValueValidator(0)],
    )
    buy_link = models.URLField(verbose_name="lien vers un site d'achat")

    nb_player_min = models.PositiveSmallIntegerField(
        verbose_name="nombre de joueur·se·s minimum"
    )
    nb_player_max = models.PositiveSmallIntegerField(
        verbose_name="nombre de joueur·se·s maximum"
    )
    player_range_precisions = models.CharField(
        max_length=256,
        blank=True,
        verbose_name="précisions sur le nombre de joueur·se·s",
        help_text="Pour indiquer une éventuelle contrainte (ex. parité) ou information sur le nombre de joueur·se·s",
    )

    duration_min = models.PositiveSmallIntegerField(
        verbose_name="durée de partie minimale",
        help_text="En minutes, telle qu'indiquée par l'éditeur",
    )
    duration_max = models.PositiveSmallIntegerField(
        verbose_name="durée de partie maximale",
        help_text="En minutes, telle qu'indiquée par l'éditeur, identique à la durée minimale si laissée vide",
        blank=True,
    )
    duration_precisions = models.CharField(
        max_length=256,
        blank=True,
        verbose_name="précisions sur la durée de partie",
        help_text="Pour indiquer des informations complémentaires sur la durée de la partie (ex. évolution en fonction du nombre de joueur·se·s)",
    )

    game_designer = models.CharField(
        max_length=256, blank=True, verbose_name="game designer"
    )
    illustrator = models.CharField(
        max_length=256, blank=True, verbose_name="illustrateur·trice"
    )
    editor = models.CharField(max_length=256, blank=True, verbose_name="éditeur")

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="catégorie",
        help_text="Idée de catégorie dans laquelle ranger ce jeu",
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        verbose_name="tags qui correspondent à ce jeu",
        help_text="Vous pouvez en sélectionner plusieurs ou aucun (sur ordinateur Ctrl+Clic change l'état de selection d'un tag)",
    )

    description = models.TextField(
        blank=True,
        verbose_name="description",
        help_text="Peut correspondre à celle de l'éditeur et ne doit pas contenir d'avis personnel",
    )

    image = models.ImageField(
        upload_to="suggestion_img/",
        blank=True,
        verbose_name="image",
        help_text="Image du jeu de moins de 512 Kio à téléverser (par exemple une photo de sa boite)",
        validators=[MaxFileSizeValidator(512)],
    )

    upvoting_users = models.ManyToManyField(
        User,
        blank=True,
        related_name="upvoted_suggestions",
        verbose_name="personnes intéressées",
    )

    class Meta:
        ordering = ["title"]
        verbose_name = "suggestion de jeu"
        verbose_name_plural = "suggestions de jeux"

    def __str__(self):
        return self.title

    def clean(self):
        if not self.nb_player_min or not self.nb_player_max or not self.duration_min:
            return
        if self.nb_player_min > self.nb_player_max:
            raise ValidationError(
                {
                    "nb_player_max": "Le nombre de joueur·se·s maximum doit être supérieur au nombre de joueur·se·s minimum"
                }
            )
        if self.duration_max is None:
            self.duration_max = self.duration_min
        if self.duration_min > self.duration_max:
            raise ValidationError(
                {
                    "duration_max": "La durée maximale doit être supérieure à la durée minimale"
                }
            )

    def get_player_range(self):
        precisions = ""
        if self.player_range_precisions:
            precisions = " ({})".format(self.player_range_precisions)
        if self.nb_player_min != self.nb_player_max:
            return "{} à {} joueur·se·s{}".format(
                self.nb_player_min, self.nb_player_max, precisions
            )
        else:
            return "{} joueur·se·s{}".format(self.nb_player_min, precisions)

    def get_duration_range(self):
        precisions = ""
        if self.duration_precisions:
            precisions = " ({})".format(self.duration_precisions)
        elif self.duration_min != self.duration_max:
            return "{} à {} min{}".format(
                self.duration_min, self.duration_max, precisions
            )
        else:
            return "{} min{}".format(self.duration_min, precisions)

    def get_absolute_url(self):
        return reverse("suggestions:suggestion", args=(self.slug,))


class SuggestionComment(AbstractComment):
    commented_object = models.ForeignKey(
        Suggestion,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="suggestion",
    )

    class Meta:
        ordering = ["created_on"]
        verbose_name = "commentaire sur une suggestion"
        verbose_name_plural = "commentaires sur des suggestions"

    def get_modification_url(self):
        return reverse(
            "suggestions:modify_suggestion_comment",
            args=(self.commented_object.slug, self.id),
        )

suggestions/forms.py
from django import forms
from .models import Suggestion


class SuggestionForm(forms.ModelForm):
    error_css_class = "errorfield"
    required_css_class = "requiredfield"

    class Meta:
        model = Suggestion
        fields = [
            "title",
            "price",
            "buy_link",
            "nb_player_min",
            "nb_player_max",
            "player_range_precisions",
            "duration_min",
            "duration_max",
            "duration_precisions",
            "category",
            "tags",
            "game_designer",
            "illustrator",
            "editor",
            "image",
            "description",
        ]


class AddSuggestionForm(SuggestionForm):
    comment = forms.CharField(widget=forms.Textarea, label="Commentaire personnel")

suggestions/views.py
from django.views.generic import ListView, DetailView, FormView, RedirectView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.db.models import Count
from comments.views import AddCommentView, ModifyCommentView
from .models import Suggestion, SuggestionComment
from .forms import AddSuggestionForm


class SuggestionListView(ListView):
    model = Suggestion
    template_name = "suggestions/suggestion_list.html"

    def get_queryset(self):
        return Suggestion.objects.annotate(
            num_upvotes=Count("upvoting_users")
        ).order_by("-num_upvotes")


class AddSuggestionView(LoginRequiredMixin, FormView):
    template_name = "suggestions/add_suggestion.html"
    form_class = AddSuggestionForm

    def form_valid(self, form):
        suggestion = form.save()
        suggestion.upvoting_users.add(self.request.user)
        suggestion.comments.create(
            author=self.request.user, text=form.cleaned_data["comment"]
        )
        messages.success(self.request, "Votre suggestion est enregistrée")
        return redirect("suggestions:suggestion", suggestion.slug)


class SuggestionView(DetailView):
    model = Suggestion
    template_name = "suggestions/suggestion.html"


class UpvoteSuggestionView(LoginRequiredMixin, SingleObjectMixin, RedirectView):
    model = Suggestion
    pattern_name = "suggestions:suggestion"

    def get_redirect_url(self, *args, **kwargs):
        suggestion = self.get_object()
        if self.request.user not in suggestion.upvoting_users.all():
            suggestion.upvoting_users.add(self.request.user)
            messages.success(
                self.request, "Votre vote pour cette suggestion est enregistré"
            )
        else:
            messages.error(self.request, "Vous avez déjà voté pour cette suggestion")

        return super().get_redirect_url(*args, **kwargs)


class DownvoteSuggestionView(LoginRequiredMixin, SingleObjectMixin, RedirectView):
    model = Suggestion
    pattern_name = "suggestions:suggestion"

    def get_redirect_url(self, *args, **kwargs):
        suggestion = self.get_object()
        if self.request.user in suggestion.upvoting_users.all():
            suggestion.upvoting_users.remove(self.request.user)
            messages.success(
                self.request, "Votre vote pour cette suggestion a été retiré"
            )
        else:
            messages.error(
                self.request, "Vous ne votiez déjà pas pour cette suggestion"
            )

        return super().get_redirect_url(*args, **kwargs)


class AddSuggestionCommentView(AddCommentView):
    model = Suggestion
    comment_model = SuggestionComment
    pattern_name = "suggestions:suggestion"


class ModifySuggestionCommentView(ModifyCommentView):
    model = Suggestion
    comment_model = SuggestionComment
    template_name = "suggestions/suggestion.html"
    success_pattern_name = "suggestions:suggestion"

suggestions/templates/suggestions/add_suggestion.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Ajout d'une suggestion</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Envoyer la suggestion</button>
  </form>
{% endblock %}

suggestions/templates/suggestions/suggestion.html
{% extends "base.html" %}
{% load static %}

{% block "content" %}
  <h1>{{ suggestion.title }}</h1>

  <div id="game_infos">
    {% if suggestion.image %}
    <img src="{{ suggestion.image.url }}" alt="{{ suggestion.title }}"/>
    {% endif %}

    <div id="details">
      <p><i class="fa fa-fw fa-money" aria-hidden="true"></i> <a href="{{ suggestion.buy_link }}" rel="nofollow">{{ suggestion.price }} €</a></p>
      <hr/>
      <p><i class="fa fa-fw fa-users" aria-hidden="true"></i> {{ suggestion.get_player_range }}</p>
      <p><i class="fa fa-fw fa-clock-o" aria-hidden="true"></i> {{ suggestion.get_duration_range }}</p>
      <hr/>
      <p><i class="fa fa-fw fa-bookmark" aria-hidden="true"></i> {% if suggestion.category %}<a href="{{ suggestion.category.get_absolute_url }}">{{ suggestion.category }}</a>{% else %}(Pas de catégorie){% endif %}</p>
      <p><i class="fa fa-fw fa-tags" aria-hidden="true"></i>
        {% for tag in suggestion.tags.all %}
          <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
        {% empty %}
          (Aucun tag)
        {% endfor %}
      </p>
      <hr/>
      <p><i class="fa fa-fw fa-wrench" aria-hidden="true"></i> {{ suggestion.game_designer|default:"(Game designer inconnu·e)" }}</p>
      <p><i class="fa fa-fw fa-paint-brush" aria-hidden="true"></i> {{ suggestion.illustrator|default:"(Illustrateur·trice inconnu·e)" }}</p>
      <p><i class="fa fa-fw fa-cogs" aria-hidden="true"></i> {{ suggestion.editor|default:"(Éditeur inconnu)" }}</p>
    </div>
  </div>

  <h2>Votes pour cette suggestion</h2>
  {% if suggestion.upvoting_users.count %}
  <p>Actuellement, {{ suggestion.upvoting_users.count }} {{ suggestion.upvoting_users.count|pluralize:"personne aimerait,personnes aimeraient" }} avoir ce jeu dans la ludothèque.</p>
  {% else %}
  <p>Pour l'instant, personne n'est intéressé par ce jeu.</p>
  {% endif %}
  {% if request.user.is_authenticated %}
  {% if request.user in suggestion.upvoting_users.all %}
  <p>Vous faites partie des personnes intéressées.</p>
  <a class="button" href="{% url "suggestions:downvote_suggestion" suggestion.slug %}"><i class="fa fa-thumbs-down" aria-hidden="true"></i> Annuler mon vote pour l'achat de ce jeu</a>
  {% else %}
  <a class="button" href="{% url "suggestions:upvote_suggestion" suggestion.slug %}"><i class="fa fa-thumbs-up" aria-hidden="true"></i> Voter pour acheter ce jeu</a>
  {% endif %}
  {% else %}
  <p><a href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Connectez-vous</a> pour voter pour une suggestion.</p>
  {% endif %}

  {% if suggestion.description %}
  <h2 id="description">Description</h2>
  {{ suggestion.description|linebreaks }}
  {% endif %}

  <h2>Avis et commentaires</h2>
  {% url "suggestions:add_suggestion_comment" suggestion.slug as add_comment_url %}
  {% include "comments.html" with comments=suggestion.comments.all %}
{% endblock %}

suggestions/templates/suggestions/suggestion_list.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Liste des suggestions</h1>
  <p>Ceci est la liste des achats suggérés par les membres du club jeux pour compléter la ludothèque.</p>
  {% for suggestion in suggestion_list %}
  {% include "./partials/suggestion_item.html" %}
  {% empty %}
  <p>(Aucune suggestion pour le moment)</p>
  {% endfor %}

  {% if request.user.is_authenticated %}
  <a class="button" href="{% url "suggestions:add_suggestion" %}"><i class="fa fa-plus" aria-hidden="true"></i> Ajouter une suggestion</a>
  {% else %}
  <p><a href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Connectez-vous</a> pour ajouter une suggestion.</p>
  {% endif %}
{% endblock %}