inventory/urls.py
from django.urls import path
from .views import (
    InventoryView,
    CategoryListView,
    CategoryView,
    TagListView,
    TagView,
    GameListView,
    GameView,
    AddGameCommentView,
    ModifyGameCommentView,
    InventorySearchView,
    GameLoanView,
    BorrowGameView,
    ReturnGameView,
    OngoingLoansView,
    DetailLoanView,
)

app_name = "inventory"

urlpatterns = [
    path("", InventoryView.as_view(), name="inventory"),
    path("category/", CategoryListView.as_view(), name="category_list"),
    path("category/<slug>/", CategoryView.as_view(), name="category"),
    path("tag/", TagListView.as_view(), name="tag_list"),
    path("tag/<slug>/", TagView.as_view(), name="tag"),
    path("game/", GameListView.as_view(), name="game_list"),
    path("game/<slug>/", GameView.as_view(), name="game"),
    path(
        "game/<slug>/add_comment", AddGameCommentView.as_view(), name="add_game_comment"
    ),
    path(
        "game/<slug>/modify_comment/<int:comment_id>",
        ModifyGameCommentView.as_view(),
        name="modify_game_comment",
    ),
    path("search/", InventorySearchView.as_view(), name="search"),
    path("loans/game/<slug>/", GameLoanView.as_view(), name="game_loan"),
    path("loans/return/<slug>/", ReturnGameView.as_view(), name="return_game"),
    path("loans/borrow/<slug>/", BorrowGameView.as_view(), name="borrow_game"),
    path("loans/ongoing/", OngoingLoansView.as_view(), name="ongoing_loans"),
    path("loans/all/", DetailLoanView.as_view(), name="all_loans"),
]

website/urls.py
from django.urls import path
from .views import MarkdownPageView

app_name = "website"

urlpatterns = [
    path("", MarkdownPageView.as_view(), {"slug": ""}, name="home"),
    path("<slug:slug>/", MarkdownPageView.as_view(), name="md_page"),
]

inventory/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from autoslug import AutoSlugField
from website.validators import MaxFileSizeValidator
from comments.models import AbstractComment
from loans.models import AbstractLoan


class Category(models.Model):
    name = models.CharField(max_length=256, verbose_name="nom", unique=True)
    slug = AutoSlugField(populate_from="name", unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "étagère"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventory:category", args=(self.slug,))


class Tag(models.Model):
    name = models.CharField(max_length=256, verbose_name="nom", unique=True)
    slug = AutoSlugField(populate_from="name", unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("inventory:tag", args=(self.slug,))


class Game(models.Model):
    title = models.CharField(verbose_name="titre du jeu", max_length=256, unique=True)
    slug = AutoSlugField(populate_from="title", unique=True)

    nb_player_min = models.PositiveSmallIntegerField(
        verbose_name="nombre de joueur·se·s minimum"
    )
    nb_player_max = models.PositiveSmallIntegerField(
        verbose_name="nombre de joueur·se·s maximum"
    )
    player_range = models.CharField(
        max_length=256,
        blank=True,
        help_text="Affichage personnalisé pour le nombre de joueur·se·s",
        verbose_name="nombre de joueur·se·s",
    )

    duration_min = models.PositiveSmallIntegerField(
        verbose_name="durée de partie minimale",
        help_text="En minutes, telle qu'indiquée par l'éditeur",
    )
    duration_max = models.PositiveSmallIntegerField(
        verbose_name="durée de partie maximale",
        help_text="En minutes, telle qu'indiquée par l'éditeur, identique à la durée minimale si laissée vide",
        blank=True,
    )
    duration = models.CharField(
        max_length=256,
        blank=True,
        help_text="Affichage personnalisé pour la durée de la partie",
        verbose_name="durée de partie",
    )

    game_designer = models.CharField(
        max_length=256, blank=True, verbose_name="game designer"
    )
    illustrator = models.CharField(
        max_length=256, blank=True, verbose_name="illustrateur·trice"
    )
    editor = models.CharField(max_length=256, blank=True, verbose_name="éditeur")

    category = models.ForeignKey(
        Category, on_delete=models.RESTRICT, verbose_name="catégorie"
    )
    tags = models.ManyToManyField(Tag, blank=True, verbose_name="tags")

    description = models.TextField(blank=True, verbose_name="description")
    image = models.ImageField(
        upload_to="game_img/",
        blank=True,
        verbose_name="image",
        help_text="L'image doit peser 512 Kio au maximum",
        validators=[MaxFileSizeValidator(512)],
    )

    missing_elements = models.TextField(blank=True, verbose_name="pièces manquantes")

    class Meta:
        ordering = ["title"]
        verbose_name = "jeu"
        verbose_name_plural = "jeux"

    def __str__(self):
        return self.title

    def clean(self):
        if not self.nb_player_min or not self.nb_player_max or not self.duration_min:
            return
        if self.nb_player_min > self.nb_player_max:
            raise ValidationError(
                {
                    "nb_player_max": "Le nombre de joueur·se·s maximum doit être supérieur au nombre de joueur·se·s minimum"
                }
            )
        if self.duration_max is None:
            self.duration_max = self.duration_min
        if self.duration_min > self.duration_max:
            raise ValidationError(
                {
                    "duration_max": "La durée maximale doit être supérieure à la durée minimale"
                }
            )

    def get_player_range(self):
        if self.player_range:
            return self.player_range
        elif self.nb_player_min != self.nb_player_max:
            return "{} à {} joueur·se·s".format(self.nb_player_min, self.nb_player_max)
        else:
            return "{} joueur·se·s".format(self.nb_player_min)

    def get_duration_range(self):
        if self.duration:
            return self.duration
        elif self.duration_min != self.duration_max:
            return "{} à {} min".format(self.duration_min, self.duration_max)
        else:
            return "{} min".format(self.duration_min)

    def get_absolute_url(self):
        return reverse("inventory:game", args=(self.slug,))


class GameComment(AbstractComment):
    commented_object = models.ForeignKey(
        Game, on_delete=models.CASCADE, related_name="comments", verbose_name="jeu"
    )

    class Meta:
        ordering = ["created_on"]
        verbose_name = "commentaire sur un jeu"
        verbose_name_plural = "commentaires sur des jeux"

    def get_modification_url(self):
        return reverse(
            "inventory:modify_game_comment", args=(self.commented_object.slug, self.id)
        )

class GameLoan(AbstractLoan):
    lent_object = models.ForeignKey(
        Game, on_delete=models.CASCADE,
        verbose_name="jeu emprunté"
    )

    class Meta(AbstractLoan.Meta):
        abstract = False
        permissions = [("can_see_loan_details", "Can see loan details")]

inventory/forms.py
from loans.forms import BorrowForm

class BorrowGameForm(BorrowForm):
    error_css_class = "errorfield"
    required_css_class = "requiredfield"

inventory/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from haystack.generic_views import SearchView
from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
from django_tables2.views import SingleTableView
from comments.views import AddCommentView, ModifyCommentView
from loans.views import BorrowView, ReturnView, DetailLoanView
from .models import Category, Tag, Game, GameComment, GameLoan
from .forms import BorrowGameForm
from .tables import LoanTable, OngoingLoansTable


class InventoryView(TemplateView):
    template_name = "inventory/inventory.html"


class CategoryListView(ListView):
    model = Category
    template_name = "inventory/category_list.html"
    paginate_by = 20


class CategoryView(DetailView):
    model = Category
    template_name = "inventory/category.html"


class TagListView(ListView):
    model = Tag
    template_name = "inventory/tag_list.html"
    paginate_by = 20


class TagView(DetailView):
    model = Tag
    template_name = "inventory/tag.html"


class GameListView(ListView):
    model = Game
    template_name = "inventory/game_list.html"
    paginate_by = 20


class GameView(DetailLoanView):
    model = Game
    loan_model = GameLoan
    template_name = "inventory/game.html"


class InventorySearchView(SearchView):
    form_class = SearchForm
    template_name = "inventory/search.html"
    paginate_by = 20

    def get_queryset(self):
        return SearchQuerySet().models(Category, Tag, Game)


class AddGameCommentView(AddCommentView):
    model = Game
    comment_model = GameComment
    pattern_name = "inventory:game"


class ModifyGameCommentView(ModifyCommentView):
    model = Game
    comment_model = GameComment
    template_name = "inventory/game.html"
    success_pattern_name = "inventory:game"


class BorrowGameView(BorrowView):
    model = Game
    loan_model = GameLoan
    template_name = "inventory/loans/borrow.html"
    form_class = BorrowGameForm
    success_pattern_name = "inventory:game_loan"


class ReturnGameView(ReturnView):
    model = GameLoan
    pattern_name = "inventory:game_loan"


class GameLoanView(DetailLoanView):
    model = Game
    loan_model = GameLoan
    template_name = "inventory/loans/game_loan.html"


class OngoingLoansView(SingleTableView):
    queryset = GameLoan.ongoing_loans()
    table_class = OngoingLoansTable
    template_name = "inventory/loans/ongoing.html"


class DetailLoanView(PermissionRequiredMixin, SingleTableView):
    permission_required = "inventory.can_see_loan_details"
    model = GameLoan
    table_class = LoanTable
    template_name = "inventory/loans/loans_table.html"

inventory/templates/inventory/category.html
{% extends "base.html" %}

{% block "content" %}
  <h1><i class="fa fa-bookmark" aria-hidden="true"></i> {{ category.name }}</h1>

  {% with game_list=category.game_set.all %}
  <p>Il y a {{ game_list|length }} jeu{{ game_list|pluralize:"x" }} dans cette
étagère&nbsp;:</p>
  {% for game in game_list %}
  {% include "./partials/game_item.html" %}
  {% endfor %}
  {% endwith %}
{% endblock %}

inventory/templates/inventory/category_list.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Liste des étagères</h1>

  <p>Il y a {{ paginator.count }} étagère{{ paginator.count|pluralize }} de jeux&nbsp;:</p>
  {% include "partials/pagination.html" %}

  {% for category in category_list %}
  {% include "./partials/category_item.html" %}
  {% endfor %}

  {% include "partials/pagination.html" %}
{% endblock %}

inventory/templates/inventory/game.html
{% extends "base.html" %}
{% load static %}

{% block "content" %}
  <h1>{{ game.title }}</h1>

  <div id="game_infos">
    {% if game.image %}
    <img src="{{ game.image.url }}" alt="{{ game.title }}"/>
    {% endif %}

    <div id="details">
      <p><i class="fa fa-fw fa-bookmark"></i> <a href="{{ game.category.get_absolute_url }}">{{ game.category }}</a></p>
      <hr/>
      <p><i class="fa fa-fw fa-users" aria-hidden="true"></i> {{ game.get_player_range }}</p>
      <p><i class="fa fa-fw fa-clock-o" aria-hidden="true"></i> {{ game.get_duration_range }}</p>
      <hr/>
      <p><i class="fa fa-fw fa-tags" aria-hidden="true"></i>
        {% for tag in game.tags.all %}
          <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
        {% empty %}
          (Aucun tag)
        {% endfor %}
      </p>
      <hr/>
      <p><i class="fa fa-fw fa-wrench" aria-hidden="true"></i> {{ game.game_designer|default:"(Game designer inconnu·e)" }}</p>
      <p><i class="fa fa-fw fa-paint-brush" aria-hidden="true"></i> {{ game.illustrator|default:"(Illustrateur·trice inconnu·e)" }}</p>
      <p><i class="fa fa-fw fa-cogs" aria-hidden="true"></i> {{ game.editor|default:"(Éditeur inconnu)" }}</p>
    </div>
  </div>

  {% if is_borrowed %}
	<p class="warning">Ce jeu est emprunté depuis le {{ loan.borrow_date }}.</p>
  {% endif %}

  <a class="button" href="{% url "inventory:game_loan" game.slug %}">
	Emprunter ou rendre « {{ game.title }} »
  </a>

  <h2 id="description">Description</h2>
  {{ object.description|linebreaks }}

  {% if game.missing_elements %}
  <h2>Pièces manquantes</h2>
  <p class="warning">{{ game.missing_elements|linebreaksbr }}</p>
  {% endif %}

  <h2>Commentaires et propositions de variantes</h2>
  {% url "inventory:add_game_comment" game.slug as add_comment_url %}
  {% include "comments.html" with comments=game.comments.all %}
{% endblock %}

inventory/templates/inventory/game_list.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Liste des jeux</h1>

  <p>Il y a {{ paginator.count }} jeu{{ paginator.count|pluralize:"x" }} en salle jeux&nbsp;:</p>
  {% include "partials/pagination.html" %}

  {% for game in game_list %}
  {% include "./partials/game_item.html" %}
  {% endfor %}

  {% include "partials/pagination.html" %}
{% endblock %}

inventory/templates/inventory/inventory.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Inventaire du club Jeux</h1>

  Rechercher dans la ludothèque:
  <form class="search" method="get" action="{% url "inventory:search" %}">
  <input type="search" name="q" />
  <button type="submit"><i class="fa fa-fw fa-search" aria-hidden="true"></i></button>
  </form>

  <hr/>

  <a class="button" href="{% url "inventory:ongoing_loans" %}">
	Emprunts en cours
  </a>
  <a class="button" href="{% url "inventory:category_list" %}">
    Liste des étagères
    <p class="helptext">
      Chaque jeu est rangé dans une unique étagère comme en salle Jeux
    </p>
  </a>
  <a class="button" href="{% url "inventory:tag_list" %}">
    Liste des tags
    <p class="helptext">
      Chaque jeu est marqué par tous les tags qui lui correspondent
    </p>
  </a>
  <a class="button" href="{% url "inventory:game_list" %}">
    Liste alphabétique
    <p class="helptext">
      La liste complète des jeux de la ludothèque
    </p>
  </a>
{% endblock %}

inventory/templates/inventory/search.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Recherche</h1>
  <form class="search" method="get">
    {{ form.q }}
    <button type="submit"><i class="fa fa-fw fa-search" aria-hidden="true"></i></button>
  </form>

  {% if query %}
    <hr/>

    {% for result in page_obj.object_list %}
      {% if result.model_name == "game" %}
        {% include "./partials/game_item.html" with game=result.object %}
      {% elif result.model_name == "category" %}
        {% include "./partials/category_item.html" with category=result.object %}
      {% elif result.model_name == "tag" %}
        {% include "./partials/tag_item.html" with tag=result.object %}
      {% endif %}
    {% empty %}
      Aucun résultat trouvé
    {% endfor %}

    {% include "partials/pagination.html" %}
  {% endif %}
{% endblock %}

inventory/templates/inventory/tag.html
{% extends "base.html" %}

{% block "content" %}
  <h1><i class="fa fa-tag" aria-hidden="true"></i> {{ tag.name }}</h1>

  {% with game_list=tag.game_set.all %}
  <p>Il y a {{ game_list|length }} jeu{{ game_list|pluralize:"x" }} marqué{{ game_list|pluralize }} avec ce tag&nbsp;:</p>
  {% for game in game_list %}
  {% include "./partials/game_item.html" %}
  {% endfor %}
  {% endwith %}
{% endblock %}

inventory/templates/inventory/tag_list.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Liste des tags</h1>

  <p>Il y a {{ paginator.count }} tag{{ paginator.count|pluralize }} dans la ludothèque&nbsp;:</p>
  {% include "partials/pagination.html" %}

  {% for tag in tag_list %}
  {% include "./partials/tag_item.html" %}
  {% endfor %}

  {% include "partials/pagination.html" %}
{% endblock %}