accounts/urls.py
from django.urls import include, path
import django.contrib.auth.views as dj_auth_views
from .views import LoginView, LogoutView, PasswordChangeView, AccountSettingsView
import django_cas_ng.views

app_name = "accounts"

cas_patterns = [
    path("login/", django_cas_ng.views.LoginView.as_view(), name="cas_ng_login"),
    path("logout/", django_cas_ng.views.LogoutView.as_view(), name="cas_ng_logout"),
    path(
        "callback/",
        django_cas_ng.views.CallbackView.as_view(),
        name="cas_ng_proxy_callback",
    ),
]

accounts_patterns = [
    path("cas/", include(cas_patterns)),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_login/", dj_auth_views.LoginView.as_view(), name="password_login"),
    path("change_password/", PasswordChangeView.as_view(), name="change_password"),
    path("settings/", AccountSettingsView.as_view(), name="account_settings"),
]

urlpatterns = [
    path("", include(accounts_patterns)),
]

inventory/urls.py
from django.urls import path
from .views import (
    InventoryView,
    CategoryListView,
    CategoryView,
    TagListView,
    TagView,
    GameListView,
    GameView,
    AddGameCommentView,
    ModifyGameCommentView,
    InventorySearchView,
    GameLoanView,
    BorrowGameView,
    ReturnGameView,
    OngoingLoansView,
    DetailLoanView,
)

app_name = "inventory"

urlpatterns = [
    path("", InventoryView.as_view(), name="inventory"),
    path("category/", CategoryListView.as_view(), name="category_list"),
    path("category/<slug>/", CategoryView.as_view(), name="category"),
    path("tag/", TagListView.as_view(), name="tag_list"),
    path("tag/<slug>/", TagView.as_view(), name="tag"),
    path("game/", GameListView.as_view(), name="game_list"),
    path("game/<slug>/", GameView.as_view(), name="game"),
    path(
        "game/<slug>/add_comment", AddGameCommentView.as_view(), name="add_game_comment"
    ),
    path(
        "game/<slug>/modify_comment/<int:comment_id>",
        ModifyGameCommentView.as_view(),
        name="modify_game_comment",
    ),
    path("search/", InventorySearchView.as_view(), name="search"),
    path("loans/game/<slug>/", GameLoanView.as_view(), name="game_loan"),
    path("loans/return/<slug>/", ReturnGameView.as_view(), name="return_game"),
    path("loans/borrow/<slug>/", BorrowGameView.as_view(), name="borrow_game"),
    path("loans/ongoing/", OngoingLoansView.as_view(), name="ongoing_loans"),
    path("loans/all/", DetailLoanView.as_view(), name="all_loans"),
]

suggestions/urls.py
from django.urls import path
from .views import (
    SuggestionListView,
    AddSuggestionView,
    SuggestionView,
    UpvoteSuggestionView,
    DownvoteSuggestionView,
    AddSuggestionCommentView,
    ModifySuggestionCommentView,
)

app_name = "suggestions"

urlpatterns = [
    path("", SuggestionListView.as_view(), name="suggestions"),
    path("add/", AddSuggestionView.as_view(), name="add_suggestion"),
    path("item/<slug>/", SuggestionView.as_view(), name="suggestion"),
    path(
        "item/<slug>/upvote", UpvoteSuggestionView.as_view(), name="upvote_suggestion"
    ),
    path(
        "item/<slug>/downvote",
        DownvoteSuggestionView.as_view(),
        name="downvote_suggestion",
    ),
    path(
        "item/<slug>/add_comment",
        AddSuggestionCommentView.as_view(),
        name="add_suggestion_comment",
    ),
    path(
        "item/<slug>/modify_comment/<int:comment_id>",
        ModifySuggestionCommentView.as_view(),
        name="modify_suggestion_comment",
    ),
]

website/urls.py
from django.urls import path
from .views import MarkdownPageView

app_name = "website"

urlpatterns = [
    path("", MarkdownPageView.as_view(), {"slug": ""}, name="home"),
    path("<slug:slug>/", MarkdownPageView.as_view(), name="md_page"),
]

website/models.py
from django.db import models
from django.urls import reverse
from markdownx.models import MarkdownxField


class MarkdownPage(models.Model):
    slug = models.SlugField(
        blank=True,
        unique=True,
        verbose_name="Adresse de la page",
        help_text="Identifiant de la page qui se voit dans l'URL. Ne doit pas collisionner avec une page existante. Laisser vide pour la page d'accueil, requis sinon.",
    )
    content = MarkdownxField(verbose_name="Contenu")

    class Meta:
        verbose_name = "page Markdown"
        verbose_name_plural = "pages Markdown"
        ordering = ["slug"]

    def __str__(self):
        return self.slug or "Page d'accueil"

    def get_absolute_url(self):
        if self.slug:
            return reverse("website:md_page", args=[self.slug])
        else:
            return reverse("website:home")

website/views.py
from django.views.generic import DetailView
from django.utils.safestring import mark_safe
from markdownx.utils import markdownify
from .models import MarkdownPage


class MarkdownPageView(DetailView):
    model = MarkdownPage
    template_name = "website/markdown_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["markdown_body"] = mark_safe(markdownify(self.object.content))
        return context

website/templates/partials/footer.html
<footer>
  Pour tout problème, contactez <tt class="antispam">rf.sne@xuejopser</tt>.
</footer>

website/templates/partials/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GestioJeux</title>
<link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}" />
<link type="image/png" rel="shortcut icon" href="{% static "img/favicon.png" %}"/>
<script src="{% static "js/jquery-3.4.1.min.js" %}"></script>

website/templates/partials/header.html
<header>
  <h1>GestioJeux</h1>

  <div id="mobile_nav_trigger" onclick="toggle_mobile_nav()">
    <i class="fa fa-fw fa-bars" aria-hidden="true"></i> Menu
  </div>

  <nav>
    {% with url_name=request.resolver_match.url_name %}
    <div>
      <a {% if url_name == "home" %}class="current"{% endif %} href="{% url "website:home" %}"><i class="fa fa-home" aria-hidden="true"></i></a>
      <a {% if url_name == "inventory" %}class="current"{% endif %} href="{% url "inventory:inventory" %}">Inventaire</a>
      <a {% if url_name == "suggestions" %}class="current"{% endif %} href="{% url "suggestions:suggestions" %}">Suggestions</a>
	  {% if perms.inventory.can_see_loan_details %}
	  <a href={% url "inventory:all_loans" %}>Gestion des emprunts</a>
	  {% endif %}
      {% if request.user.is_staff %}
      <a href="{% url "admin:index" %}">Admin</a>
      {% endif %}
    </div>
    <div id="account">
      {% if request.user.is_authenticated %}
      <a class="username" href="{% url "accounts:account_settings" %}">{{ request.user }}</a>
      <a class="logout" href="{% url "accounts:logout" %}?next={{ request.get_full_path }}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
      {% else %}
      <a class="login{% if url_name == "login" %} current{% endif %}" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Connexion</a>
      {% endif %}
    </div>
    {% endwith %}
  </nav>
</header>

website/templates/partials/messages.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %}

website/templates/partials/pagination.html
{% if page_obj.has_other_pages %}
{% load url_params %}
<div class="pagination">
  <a{% if page_obj.has_previous %} href="?{% replace_url_param request page=page_obj.previous_page_number %}"{% endif %}>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> Précédent
  </a>
  <div>
    Page {{ page_obj.number }} sur {{ paginator.num_pages }}
  </div>
  <a{% if page_obj.has_next %} href="?{% replace_url_param request page=page_obj.next_page_number %}"{% endif %}>
      Suivant <i class="fa fa-arrow-right" aria-hidden="true"></i>
  </a>
</div>
{% endif %}